### PR TITLE
Remove unused and conflicting Service Provider

### PR DESCRIPTION
**Pull request by atimbang**
Looks like it's not being used and it's clashing with the main application service provider in core application

`Warning: Ambiguous class resolution, "App\Providers\AppServiceProvider" was found 2x: in "/Users/**/Code/property-core-backend/app/Providers/AppServiceProvider.php" and "/Users/**/Code/property-core-backend/vendor/ringierimu/ringier-code-style/app/Providers/AppServiceProvider.php", the first will be used.`

### CODE REVIEW

**Comment by atimbang** [comment]
I think I need to remove it from the provider array in app.config

**Comment by atimbang** [comment]
If we need it in the future, we can consider adding it with a different name perhaps

**Comment by matthewnessworthy** [comment]
@atimbang where is this being thrown as an issue? only the binary should be downloaded

**Comment by atimbang** [comment]
> @atimbang where is this being thrown as an issue? only the binary should be downloaded

On Property when you run composer

**Comment by matthewnessworthy** [comment]
@atimbang here's what i get on property
i'm not seeing the issue you are experiencing
please provide logs to support this ticket including the commands you use to trigger said issue

`composer install`
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Google\Task\Composer::cleanup
Class DDTrace\ComposerBootstrap located in ./vendor/datadog/dd-trace/src/api/bootstrap.composer.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
146 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Illuminate\Foundation\ComposerScripts::postInstall
> @php artisan icons:clear
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)
Blade icons manifest file cleared!
> @php artisan view:clear
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)

   INFO  Compiled views cleared successfully.

> @php artisan build:publish-assets
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)

   INFO  Discovering packages.

  64robots/nova-fields ........................................................................................................................ DONE
  aws/aws-sdk-php-laravel ..................................................................................................................... DONE
  benjaminhirsch/nova-slug-field .............................................................................................................. DONE
  bensampo/laravel-enum ....................................................................................................................... DONE
  beyondcode/laravel-dump-server .............................................................................................................. DONE
  beyondcode/laravel-query-detector ........................................................................................................... DONE
  bissolli/nova-phone-field ................................................................................................................... DONE
  blade-ui-kit/blade-icons .................................................................................................................... DONE
  codebykyle/calculated-field ................................................................................................................. DONE
  digital-creative/custom-relationship-field .................................................................................................. DONE
  dillingham/nova-button ...................................................................................................................... DONE
  ebess/advanced-nova-media-library ........................................................................................................... DONE
  elegantweb/sanitizer ........................................................................................................................ DONE
  epartment/nova-dependency-container ......................................................................................................... DONE
  felixkiss/uniquewith-validator .............................................................................................................. DONE
  fideloper/proxy ............................................................................................................................. DONE
  fourstacks/nova-checkboxes .................................................................................................................. DONE
  fruitcake/laravel-cors ...................................................................................................................... DONE
  garygreen/pretty-routes ..................................................................................................................... DONE
  gobrightspot/nova-detached-actions .......................................................................................................... DONE
  inertiajs/inertia-laravel ................................................................................................................... DONE
  interaction-design-foundation/nova-html-card ................................................................................................ DONE
  intervention/image .......................................................................................................................... DONE
  izi-dev/nova-field-date-picker .............................................................................................................. DONE
  jenssegers/agent ............................................................................................................................ DONE
  kabbouchi/nova-impersonate .................................................................................................................. DONE
  koss-shtukert/laravel-nova-select2-auto-complete ............................................................................................ DONE
  lab404/laravel-impersonate .................................................................................................................. DONE
  laravel-notification-channels/sailthru-notifications-channel ................................................................................ DONE
  laravel/nova ................................................................................................................................ DONE
  laravel/passport ............................................................................................................................ DONE
  laravel/slack-notification-channel .......................................................................................................... DONE
  laravel/socialite ........................................................................................................................... DONE
  laravel/tinker .............................................................................................................................. DONE
  laravel/ui .................................................................................................................................. DONE
  laravolt/avatar ............................................................................................................................. DONE
  librenms/laravel-vue-i18n-generator ......................................................................................................... DONE
  livewire/livewire ........................................................................................................................... DONE
  llaski/nova-scheduled-jobs .................................................................................................................. DONE
  maatwebsite/excel ........................................................................................................................... DONE
  maatwebsite/laravel-nova-excel .............................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  optimistdigital/nova-translatable ........................................................................................................... DONE
  orangehill/iseed ............................................................................................................................ DONE
  orchestra/parser ............................................................................................................................ DONE
  owen-it/laravel-auditing .................................................................................................................... DONE
  propaganistas/laravel-phone ................................................................................................................. DONE
  protonemedia/laravel-analytics-event-tracking ............................................................................................... DONE
  rimu/formatted-number ....................................................................................................................... DONE
  ringierimu/agency-detail-resource-tool ...................................................................................................... DONE
  ringierimu/experiments ...................................................................................................................... DONE
  ringierimu/image-service-laravel ............................................................................................................ DONE
  ringierimu/laravel-cube-scheduler ........................................................................................................... DONE
  ringierimu/laravel-queue-start-reset-db-sticky-state ........................................................................................ DONE
  ringierimu/moderate-listing-resource-tool ................................................................................................... DONE
  ringierimu/property-core-theme .............................................................................................................. DONE
  ringierimu/sailthru-user-management ......................................................................................................... DONE
  ringierimu/search ........................................................................................................................... DONE
  ringierimu/service-bus-notifications-channel ................................................................................................ DONE
  ringierimu/state-workflow ................................................................................................................... DONE
  silviolleite/laravelpwa ..................................................................................................................... DONE
  sloveniangooner/searchable-select ........................................................................................................... DONE
  spatie/laravel-cookie-consent ............................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE
  spatie/laravel-medialibrary ................................................................................................................. DONE
  spatie/laravel-permission ................................................................................................................... DONE
  spatie/laravel-queueable-action ............................................................................................................. DONE
  spatie/laravel-responsecache ................................................................................................................ DONE
  spatie/laravel-translatable ................................................................................................................. DONE
  stechstudio/laravel-zipstream ............................................................................................................... DONE
  suenerds/nova-searchable-belongs-to-filter .................................................................................................. DONE
  tightenco/ziggy ............................................................................................................................. DONE
  vink/nova-cache-card ........................................................................................................................ DONE
  vmitchell85/nova-links ...................................................................................................................... DONE
  vyuldashev/nova-permission .................................................................................................................. DONE


   INFO  Publishing [nova-config] assets.

  File [config/nova.php] already exists .................................................................................................... SKIPPED


   INFO  Publishing [nova-assets] assets.

  Copying directory [vendor/laravel/nova/public] to [public/vendor/nova] ...................................................................... DONE


   INFO  Publishing [nova-lang] assets.

  Copying directory [vendor/laravel/nova/resources/lang] to [lang/vendor/nova] ................................................................ DONE


   INFO  Publishing [nova-views] assets.

  Copying directory [vendor/laravel/nova/resources/views/partials] to [resources/views/vendor/nova/partials] .................................. DONE


   INFO  Compiled views cleared successfully.

   INFO  Publishing [telescope-config] assets.

  File [config/telescope.php] already exists ............................................................................................... SKIPPED


   INFO  Publishing [telescope-assets] assets.

  Copying directory [vendor/laravel/telescope/public] to [public/vendor/telescope] ............................................................ DONE

Publishing Web Tinker Assets...
Web tinker installed successfully.
   INFO  Publishing [livewire:assets] assets.

  Copying directory [vendor/livewire/livewire/dist] to [public/vendor/livewire] ............................................................... DONE

> vendor/bin/ringier-code-style config:dump --pint --php-cs-fixer --phpcs --force --quiet
> vendor/bin/ringier-code-style config:dump --styleci --quiet
```

`composer dump-autoload`
```
Generating optimized autoload files
> Google\Task\Composer::cleanup
Class DDTrace\ComposerBootstrap located in ./vendor/datadog/dd-trace/src/api/bootstrap.composer.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 14127 classes
```

**Comment by atimbang** [comment]
```
composer install                                                                                                                     
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Google\Task\Composer::cleanup
Class DDTrace\ComposerBootstrap located in ./vendor/datadog/dd-trace/src/api/bootstrap.composer.php does not comply with psr-4 autoloading standard. Skipping.
Warning: Ambiguous class resolution, "App\Providers\AppServiceProvider" was found 2x: in "/Users/atimbangnkanu/Code/property-core-backend/app/Providers/AppServiceProvider.php" and "/Users/atimbangnkanu/Code/property-core-backend/vendor/ringierimu/ringier-code-style/app/Providers/AppServiceProvider.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
146 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Illuminate\Foundation\ComposerScripts::postInstall
> @php artisan icons:clear
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)
Blade icons manifest file cleared!
> @php artisan view:clear
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)

   INFO  Compiled views cleared successfully.

> @php artisan build:publish-assets
No Tenant Set, Defaulting to BRK (env:local unitTesting:false)

   INFO  Discovering packages.

  64robots/nova-fields ........................................................................................................................ DONE
  aws/aws-sdk-php-laravel ..................................................................................................................... DONE
  benjaminhirsch/nova-slug-field .............................................................................................................. DONE
  bensampo/laravel-enum ....................................................................................................................... DONE
  beyondcode/laravel-dump-server .............................................................................................................. DONE
  beyondcode/laravel-query-detector ........................................................................................................... DONE
  bissolli/nova-phone-field ................................................................................................................... DONE
  blade-ui-kit/blade-icons .................................................................................................................... DONE
  codebykyle/calculated-field ................................................................................................................. DONE
  digital-creative/custom-relationship-field .................................................................................................. DONE
  dillingham/nova-button ...................................................................................................................... DONE
  ebess/advanced-nova-media-library ........................................................................................................... DONE
  elegantweb/sanitizer ........................................................................................................................ DONE
  epartment/nova-dependency-container ......................................................................................................... DONE
  felixkiss/uniquewith-validator .............................................................................................................. DONE
  fideloper/proxy ............................................................................................................................. DONE
  fourstacks/nova-checkboxes .................................................................................................................. DONE
  fruitcake/laravel-cors ...................................................................................................................... DONE
  garygreen/pretty-routes ..................................................................................................................... DONE
  gobrightspot/nova-detached-actions .......................................................................................................... DONE
  inertiajs/inertia-laravel ................................................................................................................... DONE
  interaction-design-foundation/nova-html-card ................................................................................................ DONE
  intervention/image .......................................................................................................................... DONE
  izi-dev/nova-field-date-picker .............................................................................................................. DONE
  jenssegers/agent ............................................................................................................................ DONE
  kabbouchi/nova-impersonate .................................................................................................................. DONE
  koss-shtukert/laravel-nova-select2-auto-complete ............................................................................................ DONE
  lab404/laravel-impersonate .................................................................................................................. DONE
  laravel-notification-channels/sailthru-notifications-channel ................................................................................ DONE
  laravel/nova ................................................................................................................................ DONE
  laravel/passport ............................................................................................................................ DONE
  laravel/slack-notification-channel .......................................................................................................... DONE
  laravel/socialite ........................................................................................................................... DONE
  laravel/tinker .............................................................................................................................. DONE
  laravel/ui .................................................................................................................................. DONE
  laravolt/avatar ............................................................................................................................. DONE
  librenms/laravel-vue-i18n-generator ......................................................................................................... DONE
  livewire/livewire ........................................................................................................................... DONE
  llaski/nova-scheduled-jobs .................................................................................................................. DONE
  maatwebsite/excel ........................................................................................................................... DONE
  maatwebsite/laravel-nova-excel .............................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  optimistdigital/nova-translatable ........................................................................................................... DONE
  orangehill/iseed ............................................................................................................................ DONE
  orchestra/parser ............................................................................................................................ DONE
  owen-it/laravel-auditing .................................................................................................................... DONE
  propaganistas/laravel-phone ................................................................................................................. DONE
  protonemedia/laravel-analytics-event-tracking ............................................................................................... DONE
  rimu/formatted-number ....................................................................................................................... DONE
  ringierimu/agency-detail-resource-tool ...................................................................................................... DONE
  ringierimu/experiments ...................................................................................................................... DONE
  ringierimu/image-service-laravel ............................................................................................................ DONE
  ringierimu/laravel-cube-scheduler ........................................................................................................... DONE
  ringierimu/laravel-queue-start-reset-db-sticky-state ........................................................................................ DONE
  ringierimu/moderate-listing-resource-tool ................................................................................................... DONE
  ringierimu/property-core-theme .............................................................................................................. DONE
  ringierimu/sailthru-user-management ......................................................................................................... DONE
  ringierimu/search ........................................................................................................................... DONE
  ringierimu/service-bus-notifications-channel ................................................................................................ DONE
  ringierimu/state-workflow ................................................................................................................... DONE
  silviolleite/laravelpwa ..................................................................................................................... DONE
  sloveniangooner/searchable-select ........................................................................................................... DONE
  spatie/laravel-cookie-consent ............................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE
  spatie/laravel-medialibrary ................................................................................................................. DONE
  spatie/laravel-permission ................................................................................................................... DONE
  spatie/laravel-queueable-action ............................................................................................................. DONE
  spatie/laravel-responsecache ................................................................................................................ DONE
  spatie/laravel-translatable ................................................................................................................. DONE
  stechstudio/laravel-zipstream ............................................................................................................... DONE
  suenerds/nova-searchable-belongs-to-filter .................................................................................................. DONE
  tightenco/ziggy ............................................................................................................................. DONE
  vink/nova-cache-card ........................................................................................................................ DONE
  vmitchell85/nova-links ...................................................................................................................... DONE
  vyuldashev/nova-permission .................................................................................................................. DONE


   INFO  Publishing [nova-config] assets.

  File [config/nova.php] already exists .................................................................................................... SKIPPED


   INFO  Publishing [nova-assets] assets.

  Copying directory [vendor/laravel/nova/public] to [public/vendor/nova] ...................................................................... DONE


   INFO  Publishing [nova-lang] assets.

  Copying directory [vendor/laravel/nova/resources/lang] to [resources/lang/vendor/nova] ...................................................... DONE


   INFO  Publishing [nova-views] assets.

  Copying directory [vendor/laravel/nova/resources/views/partials] to [resources/views/vendor/nova/partials] .................................. DONE


   INFO  Compiled views cleared successfully.

   INFO  Publishing [telescope-config] assets.

  File [config/telescope.php] already exists ............................................................................................... SKIPPED


   INFO  Publishing [telescope-assets] assets.

  Copying directory [vendor/laravel/telescope/public] to [public/vendor/telescope] ............................................................ DONE

Publishing Web Tinker Assets...
Web tinker installed successfully.
   INFO  Publishing [livewire:assets] assets.

  Copying directory [vendor/livewire/livewire/dist] to [public/vendor/livewire] ............................................................... DONE

> vendor/bin/ringier-code-style config:dump --pint --php-cs-fixer --phpcs --force --quiet
> vendor/bin/ringier-code-style config:dump --styleci --quiet
```

**Comment by atimbang** [comment]
@matthewnessworthy see above

**Comment by matthewnessworthy** [comment]
@atimbang please try delete your `./vendor` folder and `composer install` again ... those .php files you mention inside `vendor/ringierimu/ringier-code-style/` have not existed for a while now, i can only assume you somehow have an install from source version

**Comment by atimbang** [comment]
@matthewnessworthy you're right, it works fine now after deleting the vendor folder..

**Pull request closed without merging**
